### ISSUE TITLE
Async timeout too short in install task

### ISSUE THREAD

**Issue by jknaus** [geerlingguy/ansible-role-gitlab#162]
With the given `async: 300` setting in the `Install Gitlab` task my installation never succeeded:
```
TASK [geerlingguy.gitlab : Install GitLab] *********************************************************************************************
fatal: [testvm]: FAILED! => {"changed": false, "msg": "async task did not complete within the requested time - 300s"}
```
I changed it to `60000` (might be too high, actually) and then it worked.

Maybe the timeout could better be a variable in `defaults/main.yml`?

**Comment by mglantz** [comment]
I also have to change this, 600 worked for me. It's a huuuge package and a lot of post actions, so 300 is not enough.

**Comment by mglantz** [comment]
I've created pull request https://github.com/geerlingguy/ansible-role-gitlab/pull/163 for this

**Comment by szengerle** [comment]
Timeout as well in my case. I removed the async statement entirely. What was the intent to use async?

Br,
Sebastian

**Comment by ch-e-mistry** [comment]
Timeout for me as well:
`TASK [geerlingguy.gitlab : Install GitLab] *************************************
fatal: [ubu-gitlab]: FAILED! => {"changed": false, "msg": "async task did not complete within the requested time - 300s"}`

My usecase: vagrant with:
 *  Ubuntu 16.04.7 LTS
 * 4GB mem

fix was to increase async, however would be fine to have a long-term solution (fixed in role).

Thanks in advice.

Br,

**Comment by arkag** [comment]
FWIW I'm running into this as well. Unsure what's causing it to work quickly on local VMs and not in EC2 instances, as the local VMs don't get the timeout.
